import type { ThemeTokens, LocaleStrings } from './index.js'

export const DEFAULT_THEME_TOKENS: ThemeTokens = {
  primary: '#6366f1',
  primaryFg: '#ffffff',
  primaryHover: '#4f46e5',
  surface: '#ffffff',
  surfaceRaised: '#f9fafb',
  overlay: 'rgba(0,0,0,0.45)',
  text: '#111827',
  textMuted: '#6b7280',
  border: '#e5e7eb',
  focusRing: '#6366f1',
  danger: '#ef4444',
  success: '#22c55e',
  warning: '#f59e0b',
  toolbarBg: '#f3f4f6',
  paletteBg: '#ffffff',
  canvasBg: '#e5e7eb',
  fieldActive: 'rgba(99,102,241,0.18)',
  fieldRequired: 'rgba(239,68,68,0.15)',
  fieldComplete: 'rgba(34,197,94,0.15)',
  sigInk: '#1e293b',
  sigFont: '"Dancing Script", cursive',
  radiusSm: '4px',
  radius: '8px',
  radiusLg: '12px',
  fontUi: 'inherit',
  zOverlay: '100',
  shadow: '0 1px 3px rgba(0,0,0,0.1)',
}

export const DEFAULT_LOCALE: LocaleStrings = {
  toolbarZoomIn: 'Zoom in',
  toolbarZoomOut: 'Zoom out',
  toolbarFitPage: 'Fit page',
  toolbarFitWidth: 'Fit width',
  toolbarDownload: 'Download',
  toolbarSave: 'Save template',
  toolbarPageOf: '{current} of {total}',
  paletteTitle: 'Fields',
  paletteSearch: 'Search fields…',
  paletteEmpty: 'No fields match',
  fieldTypeSignature: 'Signature',
  fieldTypeInitials: 'Initials',
  fieldTypeDateSigned: 'Date signed',
  fieldTypeText: 'Text',
  fieldTypeTextarea: 'Multiline text',
  fieldTypeCheckbox: 'Checkbox',
  fieldTypeRadio: 'Radio',
  fieldTypeDropdown: 'Dropdown',
  fieldTypeStamp: 'Stamp',
  fieldRequired: 'Required',
  fieldOptional: 'Optional',
  fieldAssignedTo: 'Assigned to {name}',
  sigModalTitle: 'Add your signature',
  sigTabDraw: 'Draw',
  sigTabType: 'Type',
  sigTabUpload: 'Upload',
  sigDrawInstructions: 'Draw your signature below',
  sigTypeLabel: 'Type your name',
  sigTypeSelectFont: 'Select style',
  sigUploadInstructions: 'Upload an image of your signature',
  sigClear: 'Clear',
  sigConfirm: 'Apply',
  sigCancel: 'Cancel',
  signProgress: '{done} of {total} fields complete',
  signSubmit: 'Submit signed document',
  signDecline: 'Decline to sign',
  signDeclineReason: 'Reason for declining (optional)',
  signDeclineConfirm: 'Confirm decline',
  validationRequired: 'This field is required',
  validationPattern: 'Invalid format',
  validationEmail: 'Enter a valid email address',
  validationPhone: 'Enter a valid phone number',
  validationNumber: 'Enter a valid number',
  validationMinLength: 'Minimum {min} characters',
  validationMaxLength: 'Maximum {max} characters',
  exportGenerating: 'Generating document…',
  exportSuccess: 'Document ready',
  exportError: 'Export failed',
  stateLoading: 'Loading document…',
  stateError: 'Something went wrong',
  stateEmpty: 'No document loaded',
}
