import type { PdfTemplate, SigningResult, AuditEntry } from '../types/index.js'

export interface AuditPageContext {
  pdfDoc: {
    addPage: (size: [number, number]) => unknown
  }
  page: {
    drawText: (text: string, options: Record<string, unknown>) => void
    drawRectangle: (options: Record<string, unknown>) => void
    drawLine: (options: Record<string, unknown>) => void
    getSize: () => { width: number; height: number }
  }
  fonts: {
    helvetica: unknown
    helveticaBold: unknown
  }
  rgb: (r: number, g: number, b: number) => unknown
}

const MARGIN = 50
const LINE_HEIGHT = 16

/**
 * Build the text content for the audit certificate.
 * Returns an ordered list of { text, bold, indent } lines.
 * Separated from rendering so it can be unit-tested without pdf-lib.
 */
export function buildAuditLines(
  result: SigningResult,
  template: PdfTemplate,
): Array<{ text: string; bold: boolean; indent: number }> {
  const lines: Array<{ text: string; bold: boolean; indent: number }> = []

  const push = (text: string, bold = false, indent = 0) =>
    lines.push({ text, bold, indent })

  push('Document Signing Certificate', true)
  push('')
  push(`Generated: ${new Date(result.completedAt).toUTCString()}`)
  push('')

  // Document section
  push('Document', true)
  push(`  Original hash (SHA-256):  ${template.pdfHash}`, false, 2)
  push(`  Final hash (SHA-256):     ${result.finalPdfHash}`, false, 2)
  push(`  Pages:                    ${template.pageCount}`, false, 2)
  push(`  Fields placed:            ${template.fields.length}`, false, 2)
  push('')

  // Signers section
  push('Signers', true)
  for (const signer of template.signers) {
    push(`  ${signer.name}${signer.email ? ` <${signer.email}>` : ''}`, false, 2)
    push(`    Signer ID: ${signer.id}`, false, 4)
    push(`    Sign order: ${signer.order}`, false, 4)
  }
  push('')

  // Completed fields section
  push('Completed Fields', true)
  for (const completed of result.completedValues) {
    const field = template.fields.find((f) => f.id === completed.fieldId)
    const signer = template.signers.find((s) => s.id === completed.signerId)
    const label = field?.label ?? completed.fieldId
    const signerName = signer?.name ?? completed.signerId
    const timestamp = new Date(completed.completedAt).toUTCString()

    push(`  ${label}`, false, 2)
    push(`    Completed by: ${signerName}`, false, 4)
    push(`    At:           ${timestamp}`, false, 4)
    push(`    Type:         ${field?.type ?? 'unknown'}`, false, 4)
    push(`    Required:     ${field?.required ? 'Yes' : 'No'}`, false, 4)
    push(`    Page:         ${(field?.rect.page ?? 0) + 1}`, false, 4)
  }
  push('')

  // Audit trail section
  push('Audit Trail', true)
  for (const entry of result.auditTrail) {
    push(`  ${formatAuditEvent(entry)}`, false, 2)
    if (entry.ipAddress) push(`    IP: ${entry.ipAddress}`, false, 4)
    if (entry.userAgent) {
      const ua = entry.userAgent.length > 60
        ? entry.userAgent.slice(0, 57) + '...'
        : entry.userAgent
      push(`    UA: ${ua}`, false, 4)
    }
  }
  push('')

  // Footer
  push('─'.repeat(60))
  push('This certificate was generated by pdf-sign.')
  push('Verify document integrity by hashing the completed PDF')
  push('and comparing against the Final hash above.')

  return lines
}

function formatAuditEvent(entry: AuditEntry): string {
  const ts = new Date(entry.timestamp).toUTCString()
  switch (entry.event) {
    case 'document-opened':
      return `[${ts}] Document opened`
    case 'field-completed':
      return `[${ts}] Field completed: ${entry.fieldId ?? ''} by ${entry.signerId ?? ''}`
    case 'document-submitted':
      return `[${ts}] Document submitted by ${entry.signerId ?? ''}`
    case 'document-declined':
      return `[${ts}] Document declined by ${entry.signerId ?? ''}`
    default:
      return `[${ts}] ${entry.event}`
  }
}

/**
 * Render the audit certificate lines onto the provided pdf-lib page.
 * Call after buildAuditLines().
 */
export function renderAuditPage(
  lines: Array<{ text: string; bold: boolean; indent: number }>,
  ctx: AuditPageContext,
): void {
  const { width, height } = ctx.page.getSize()
  let y = height - MARGIN

  // Header bar
  ctx.page.drawRectangle({
    x: 0,
    y: height - 40,
    width,
    height: 40,
    color: ctx.rgb(0.24, 0.25, 0.95 * 0.5), // muted indigo
  })

  // Draw each line
  for (const line of lines) {
    if (line.text === '') {
      y -= LINE_HEIGHT * 0.5
      continue
    }

    // Section divider
    if (line.text.startsWith('─')) {
      ctx.page.drawLine({
        start: { x: MARGIN, y },
        end: { x: width - MARGIN, y },
        thickness: 0.5,
        color: ctx.rgb(0.7, 0.7, 0.7),
      })
      y -= LINE_HEIGHT
      continue
    }

    // Page overflow — lines that overflow are truncated
    if (y < MARGIN + LINE_HEIGHT) break

    const fontSize = line.bold ? 11 : 9
    const font = line.bold ? ctx.fonts.helveticaBold : ctx.fonts.helvetica
    const color = line.bold
      ? ctx.rgb(0.1, 0.1, 0.5)
      : ctx.rgb(0.2, 0.2, 0.2)

    const x = MARGIN + line.indent * 4

    ctx.page.drawText(line.text.trimEnd(), {
      x,
      y: y - fontSize,
      size: fontSize,
      font,
      color,
      maxWidth: width - MARGIN - x,
    })

    y -= line.bold ? LINE_HEIGHT + 4 : LINE_HEIGHT
  }
}

